version: '2'

services:
  gerrit:
    image: openfrontier/gerrit:latest
    hostname: gerrit
    domainname: traviszheng.net
    container_name: gerrit
    ports:
    - "8080:8080"
    - "29418:29418"
    volumes:
    - /srv/docker/gerrit/gerrit_site:/var/gerrit/review_site
    environment:
    - WEBURL=http://gerrit.traviszheng.net:8080
    - AUTH_TYPE=HTTP
    restart: always
