version: '2'

services:
  gerrit:
    image: openfrontier/gerrit:2.15.2
    hostname: gerrit
    domainname: njdongshang.net
    container_name: gerrit
    ports:
    - "10082:8080"
    - "29418:29418"
    volumes:
    - /srv/docker/gerrit/gerrit_site:/var/gerrit/review_site
    environment:
    - WEBURL=http://gerrit.njdongshang.net
    - AUTH_TYPE=LDAP
    - LDAP_SERVER=ldap://ldap.njdongshang.net
    - LDAP_ACCOUNTBASE=ou=people,dc=traviszheng,dc=net
    extra_hosts:
    - "ldap.njdongshang.net:192.168.1.110"
    restart: always
