version: '2'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '443:443'
      - '20081:20081'
      - '20082:20082'
      - '20083:20083'
      - '20084:20084'
      - '20085:20085'
    environment:
      - NGINX_HOST=www.traviszheng.net
      - NGINX_PORT=80
    volumes:
      - '/srv/docker/nginx/nginx_site:/etc/nginx/conf.d'
      - '/srv/docker/nginx/nginx_data:/home/nginx/data'
      - '/srv/docker/nginx/nginx_www:/home/nginx/www'
    restart: always
    extra_hosts:
     - "njdongshang.net:192.168.1.110"
     - "www.njdongshang.net:192.168.1.110"

