version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: traviszheng.net
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - /srv/docker/mailserver/maildata:/var/mail
    - /srv/docker/mailserver/mailstate:/var/mail-state
    - /srv/docker/mailserver/config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=0
    - ONE_DIR=1
    - DMS_DEBUG=0
    - ENABLE_LDAP=1
    - LDAP_SERVER_HOST=192.168.1.107 # your ldap container/IP/ServerName
    - LDAP_SEARCH_BASE=ou=people,dc=traviszheng,dc=net
    - LDAP_BIND_DN=cn=admin,dc=traviszheng,dc=net
    - LDAP_BIND_PW=admin
    - LDAP_QUERY_FILTER_USER="(&(mail=%s)(mailEnabled=TRUE))"
    - LDAP_QUERY_FILTER_GROUP="(&(mailGroupMember=%s)(mailEnabled=TRUE))"
    - LDAP_QUERY_FILTER_ALIAS="(&(mailAlias=%s)(mailEnabled=TRUE))"
    - DOVECOT_PASS_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
    - DOVECOT_USER_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
    - ENABLE_SASLAUTHD=1
    - SASLAUTHD_MECHANISMS=ldap
    - SASLAUTHD_LDAP_SERVER=192.168.1.107
    - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=traviszheng,dc=net
    - SASLAUTHD_LDAP_PASSWORD=admin
    - SASLAUTHD_LDAP_SEARCH_BASE=ou=people,dc=traviszheng,dc=net
    - POSTMASTER_ADDRESS=admin@traviszheng.net
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
