version: '2'
services:
  jenkins:
    image: 'bitnami/jenkins:latest'
    ports:
      - '10084:8080'
      - '9443:8443'
    volumes:
      - '/srv/docker/jenkins/jenkins_data:/bitnami'
volumes:
  jenkins_data:
    driver: local
